"""Add all Phase 2 models

Revision ID: 0fa5dbbb215f
Revises: 
Create Date: 2025-12-23 10:13:05.322344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa5dbbb215f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_owner_id'), ['owner_id'], unique=False)

    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_templates_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_templates_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_templates_team_id'), ['team_id'], unique=False)

    op.create_table('team_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('invitation_token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'expired', name='invitation_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invitations_invitation_token'), ['invitation_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_team_invitations_team_id'), ['team_id'], unique=False)

    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='member_role'), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='unique_team_user')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_user_id'), ['user_id'], unique=False)

    op.create_table('call_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('audio_file_path', sa.String(length=500), nullable=True),
    sa.Column('audio_duration', sa.Integer(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_analyses_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_analyses_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_analyses_user_id'), ['user_id'], unique=False)

    op.create_table('template_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('field_label', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.Enum('text', 'number', 'long_text', 'dropdown', 'multi_select', name='field_type'), nullable=False),
    sa.Column('field_options', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('template_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_fields_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_template_fields_template_id'), ['template_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'finalized', name='report_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['call_analyses.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)

    op.create_table('report_field_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['template_fields.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_field_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_field_values_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_field_values_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_field_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_field_values_report_id'))
        batch_op.drop_index(batch_op.f('ix_report_field_values_field_id'))

    op.drop_table('report_field_values')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_reports_template_id'))
        batch_op.drop_index(batch_op.f('ix_reports_team_id'))
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))

    op.drop_table('reports')
    with op.batch_alter_table('template_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_fields_template_id'))
        batch_op.drop_index(batch_op.f('ix_template_fields_display_order'))

    op.drop_table('template_fields')
    with op.batch_alter_table('call_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_call_analyses_template_id'))
        batch_op.drop_index(batch_op.f('ix_call_analyses_team_id'))
        batch_op.drop_index(batch_op.f('ix_call_analyses_created_at'))

    op.drop_table('call_analyses')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_team_id'))

    op.drop_table('team_members')
    with op.batch_alter_table('team_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_invitations_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_invitations_invitation_token'))
        batch_op.drop_index(batch_op.f('ix_team_invitations_email'))

    op.drop_table('team_invitations')
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_templates_team_id'))
        batch_op.drop_index(batch_op.f('ix_report_templates_is_active'))
        batch_op.drop_index(batch_op.f('ix_report_templates_created_by'))

    op.drop_table('report_templates')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_owner_id'))

    op.drop_table('teams')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
